### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by chenyu19880302** [yirueilu-b/BlazePalmTF2#1]
Thank you for your shares! Can you provide the hand datasets？

**Comment by yirueilu-b** [comment]
> Thank you for your shares! Can you provide the hand datasets？

I didn’t train this model with a formal dataset, instead I collected data by using MediaPipe’s official released model (around 150 images) just for verifying if model works correctly.
You may check out another repo HandTracking here for inferencing and saving data with their trained model or use the annotation tools like labelme to collect your own data.
